//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelListing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelListing.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thành công.
        /// </summary>
        public static string COMFIRMED_SUCCESS {
            get {
                return ResourceManager.GetString("COMFIRMED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thành công.
        /// </summary>
        public static string CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string FORGOT_PASSWORD_BODY {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào mail để lấy link thay đổi mật khẩu.
        /// </summary>
        public static string FORGOT_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string GET_SUCCESS {
            get {
                return ResourceManager.GetString("GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string LOGIN_FAIL {
            get {
                return ResourceManager.GetString("LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thất bại.
        /// </summary>
        public static string LOGOUT_FAIL {
            get {
                return ResourceManager.GetString("LOGOUT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string LOGOUT_SUCCESS {
            get {
                return ResourceManager.GetString("LOGOUT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        public static string NOT_ACCOUNT {
            get {
                return ResourceManager.GetString("NOT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string NOT_DATA {
            get {
                return ResourceManager.GetString("NOT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có mã.
        /// </summary>
        public static string NOT_TOKEN {
            get {
                return ResourceManager.GetString("NOT_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí thành công.
        /// </summary>
        public static string REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công.
        /// </summary>
        public static string RESETPASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("RESETPASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận địa chỉ Email.
        /// </summary>
        public static string SEND_MAIL_CONFIRMED {
            get {
                return ResourceManager.GetString("SEND_MAIL_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận Email bằng cách ấn vào link sau.
        /// </summary>
        public static string SEND_MAIL_CONFIRMED_BODY {
            get {
                return ResourceManager.GetString("SEND_MAIL_CONFIRMED_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có dạng giống nhau.
        /// </summary>
        public static string VALIDATION_COMPARE {
            get {
                return ResourceManager.GetString("VALIDATION_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải đúng dạng của {0}.
        /// </summary>
        public static string VALIDATION_DISPLAY {
            get {
                return ResourceManager.GetString("VALIDATION_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài lớn nhất của {0} là {1} kí tự.
        /// </summary>
        public static string VALIDATION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài nhỏ nhất của {0} là {1} kí tự.
        /// </summary>
        public static string VALIDATION_MIN_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống {0}.
        /// </summary>
        public static string VALIDATION_NOT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_EMPTY", resourceCulture);
            }
        }
    }
}
